apiVersion: v1
kind: Service
metadata:
  name: bankapp-service
  namespace: bankapp
spec:
  type: NodePort
  selector:  # ← THIS WAS MISSING!
    app: bankapp  # ← This must match your deployment's pod labels
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30000